# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faves', '0004_auto_20161027_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='frequency',
            new_name='frequency_id',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='user',
            new_name='user_id',
        ),
    ]
