# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161025_2125'),
        ('faves', '0005_auto_20161027_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
