# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faves', '0005_auto_20161027_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
    ]
