# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faves', '0007_auto_20161027_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequency',
            options={'managed': True},
        ),
    ]
